// Clave JWT para la autenticación con Pinata.
export const PINATA_JWT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJkZDZiNjI0ZS0zMmIxLTQ5ODktOWM2Ny1iZTM4YmZjMDAxYTMiLCJlbWFpbCI6ImNyaXN0aWFuMXZpbmRhc0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiYjgxZTE4MWQ3M2FlMDc5Mzg5MWEiLCJzY29wZWRLZXlTZWNyZXQiOiI0ZmUxZGJhYTIyYjNjNjhjZmQwYzcyYzZiODBiYjAzNjgxZGVkY2QwNmEzM2VjYzFkOGE3ZmNkNDM3Zjc1YmQ5IiwiZXhwIjoxNzg2MjkwNDA4fQ.V6G5iAvWkZpr6Q-SgIYiChjhrQ357_PJm_XWGGFuvu8";

// Gateway público de Pinata para acceder a los archivos subidos.
export const PINATA_GATEWAY = 'gateway.pinata.cloud';
